add

diff --git a/.github/workflows/runtime_build_and_test.yml b/.github/workflows/runtime_build_and_test.yml
--- a/.github/workflows/runtime_build_and_test.yml
+++ b/.github/workflows/runtime_build_and_test.yml
@@ -211,7 +211,7 @@ jobs:
       - name: Yarn cache
         run: |
           cacheDir=$(yarn cache dir);
-          tree -f cacheDir;
+          tree -f $cacheDir || echo "not found $cacheDir";
           # yarn cache clean;
       - name: Lint build
         run: yarn lint-build
